version = "1.0"

[jobs]

[jobs.build]
description = "Build the project"
steps = [
    "cargo build --release"
]

[jobs.lint]
description = "Run Clippy lint checks"
steps = [
    "cargo clippy"
]
depend_on = ["build"]

[jobs.test]
description = "Run tests"
steps = [
    "cargo test --all"
]
depends_on = ["build"]

[jobs.deploy]
description = "Run deployment script"
steps = [
    "deploy.bat"
]
depends_on = ["test"]

# Linux System
#[jobs]
#
#[jobs.build]
#description = "Build the project"
#steps = [
#    "mkdir -p logs",
#    "cargo build --release 2>&1 | tee logs/build.log"
#]
#
#[jobs.lint]
#description = "Run Clippy lint checks"
#steps = [
#    "cargo clippy -- -D warnings 2>&1 | tee logs/lint.log"
#]
#
#[jobs.test]
#description = "Run tests"
#steps = [
#    "cargo test --all 2>&1 | tee logs/test.log"
#]
#
#[jobs.deploy]
#description = "Run deployment script"
#steps = [
#    "./deploy.bat 2>&1 | tee logs/deploy.log"
#]
